channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip

  - pytorch
  - torchvision
  - transformers
  - pytorch-lightning

  - pandas
  - rich
  - openpyxl
  - scikit-learn
  - typer
  - wandb

  - black
  - flake8
  - flake8-bugbear
  - isort
  - mypy
  - pre-commit

  - pip:
      - pytorch_optimizer
